name: chatgpt_examples
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  flutter_riverpod: ^2.3.7
  loading_indicator: ^3.1.1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.0
  http_parser: ^4.0.2
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - .env